repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -s -w -e .
        language: system
        pass_filenames: false
      - id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt -recursive examples tests
        language: system
        pass_filenames: false
